# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Prowlarr:
        label: "Search Gateway"
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_NAS_IP}}:9696
        container: prowlarr
        widget:
          type: prowlarr
          url: http://{{HOMEPAGE_VAR_NAS_IP}}:9696
          key: {{HOMEPAGE_VAR_KEY_PROWLARR}}

- Acquisition Engines:
    - Torrent:
        label: "Acquistion Node"
        icon: rutorrent.png
        href: http://{{HOMEPAGE_VAR_NAS_IP}}:8080
        container: torrent
        widget:
          type: rutorrent
          url: http://{{HOMEPAGE_VAR_NAS_IP}}:8080
#    - JDownloader:
#        label: "Web Collector"
#        icon: jdownloader.png
#        href: http://{{HOMEPAGE_VAR_NAS_IP}}:5800
#        container: jdownloader
#        widget:
#          type: jdownloader
#          url: http://127.0.0.1:5800

- Curatorial Tools:
    - Whisparr:
        label: "Content Librarian"
        icon: whisparr.png
        href: http://{{HOMEPAGE_VAR_NAS_IP}}:6969
        container: whisparr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_NAS_IP}}:6969
          key: {{HOMEPAGE_VAR_KEY_WHISPARR}}

    - Stash:
        label: "Archive Vault"
        icon: stash.png
        href: http://{{HOMEPAGE_VAR_NAS_IP}}:9999
        container: stash
        widget:
          type: stash
          url: http://{{HOMEPAGE_VAR_NAS_IP}}:9999
          key: {{HOMEPAGE_VAR_KEY_STASH}}
          fields: ["scenes", "performers", "studios", "galleries"]

- Digital Theater:
    - Jellyfin:
        label: "The Grand Cinema"
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_NAS_IP}}:8096
        container: jellyfin
        widget:
          type: jellyfin
          url: http://127.0.0.1:8096
          key: {{HOMEPAGE_VAR_KEY_JELLYFIN}}

- Tailscale:
    - Deneb:
        icon: tailscale.png
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_DEVICEID_DENEB}}
          key: {{HOMEPAGE_VAR_KEY_TAILSCALE}}
    - Agrias:
        icon: tailscale.png
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_DEVICEID_AGRIAS}}
          key: {{HOMEPAGE_VAR_KEY_TAILSCALE}}
    - Deck:
        icon: tailscale.png
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_DEVICEID_DECK}}
          key: {{HOMEPAGE_VAR_KEY_TAILSCALE}}

    - Mini:
        icon: tailscale.png
        widget:
          type: tailscale
          deviceid: {{HOMEPAGE_VAR_DEVICEID_MINI}}
          key: {{HOMEPAGE_VAR_KEY_TAILSCALE}}
