- Infrastructure:
    - Prowlarr:
        label: "Search Gateway"
        icon: prowlarr.png
        href: http://192.168.1.108:9696
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: YOUR_PROWLARR_API_KEY

- Acquisition Engines:
    - ruTorrent:
        label: "Direct Inbound"
        icon: rutorrent.png
        href: http://192.168.1.108:8080
        container: rtorrent-rutorrent
        widget:
          type: rutorrent
          url: http://rtorrent-rutorrent:8080
    - JDownloader:
        label: "Web Collector"
        icon: jdownloader.png
        href: http://192.168.1.108:5800
        container: jdownloader
        widget:
          type: jdownloader
          url: http://jdownloader:5800

- Curatorial Tools:
    - Whisparr:
        label: "Content Librarian"
        icon: whisparr.png
        href: http://192.168.1.108:6969
        container: whisparr
        widget:
          type: whisparr
          url: http://whisparr:6969
          key: YOUR_WHISPARR_API_KEY
    - Stash:
        label: "Archive Vault"
        icon: stash.png
        href: http://192.168.1.108:9999
        container: stash
        widget:
          type: stash
          url: http://stash:9999
          key: YOUR_STASH_API_KEY

- Digital Theater:
    - Jellyfin:
        label: "The Grand Cinema"
        icon: jellyfin.png
        href: http://192.168.1.108:8096
        container: jellyfin
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: YOUR_JELLYFIN_API_KEY
